version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
  build:
    commands:
      - sam build
      - sam package --output-template-file packaged.yaml --s3-bucket epam-asobolev-test-website
  post_build:
    commands:
      - sam deploy --template-file packaged.yaml --stack-name lambda-notification-stack --capabilities CAPABILITY_IAM --no-fail-on-empty-changeset
