version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
  build:
    commands:
      - sam build
      - sam package --output-template-file packaged.yaml --s3-bucket epam-asobolev-test-website
